name: Cypress App-Builder

on:
  pull_request_target:
    types: [labeled, unlabeled, closed]
  workflow_dispatch:

env:
  PR_NUMBER: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TOOLJET_HOST: http://localhost:8082

jobs:
  Cypress-App-Builder:
    runs-on: ubuntu-22.04

    if: |
      github.event.action == 'labeled' &&
      (
        github.event.label.name == 'run-cypress' || 
        github.event.label.name == 'run-ce-app-builder' || 
        github.event.label.name == 'run-ee-app-builder'
      )

    strategy:
      matrix:
        edition: >-
          ${{ 
            contains(github.event.pull_request.labels.*.name, 'run-cypress') && fromJson('["ce", "ee"]') ||
            contains(github.event.pull_request.labels.*.name, 'run-ce-app-builder') && fromJson('["ce"]') ||
            contains(github.event.pull_request.labels.*.name, 'run-ee-app-builder') && fromJson('["ee"]') ||
            fromJson('[]')
          }}

    steps:
      # Step 1: Set up Git authentication for private submodules
      - name: Set up Git Authentication for Private Submodules
        run: |
          git config --global url."https://x-access-token:${{ secrets.CUSTOM_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      # Step 2: Checkout the repository with submodules
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      # Step 3: Ensure correct branch for submodules (EE edition only)
      - name: Checkout Correct Branch for Submodules (EE Edition)
        if: matrix.edition == 'ee'
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive '
            git checkout ${{ env.BRANCH_NAME }} 2>/dev/null || git checkout main'

      # Step 4: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2

      # Step 5: Install dependencies and build
      - name: Install and Build Dependencies
        run: |
          npm cache clean --force
          npm install
          npm install --prefix server
          npm install --prefix frontend
          npm run build:plugins

      # Step 6: Set up environment variables
      - name: Set up Environment Variables
        run: |
          echo "TOOLJET_HOST=${{ env.TOOLJET_HOST }}" >> .env
          echo "LOCKBOX_MASTER_KEY=cd97331a419c09387bef49787f7da8d2a81d30733f0de6bed23ad8356d2068b2" >> .env
          echo "SECRET_KEY_BASE=7073b9a35a15dd20914ae17e36a693093f25b74b96517a5fec461fc901c51e011cd142c731bee48c5081ec8bac321c1f259ef097ef2a16f25df17a3798c03426" >> .env
          echo "PG_DB=tooljet_development" >> .env
          echo "PG_USER=postgres" >> .env
          echo "PG_HOST=localhost" >> .env
          echo "PG_PASS=postgres" >> .env
          echo "PG_PORT=5432" >> .env
          echo "ENABLE_TOOLJET_DB=true" >> .env
          echo "PGRST_JWT_SECRET=r9iMKoe5CRMgvJBBtp4HrqN7QiPpUToj" >> .env

      # Step 7: Set up database
      - name: Set up Database
        run: |
          npm run --prefix server db:create
          npm run --prefix server db:reset

      # Step 8: Wait for the server to be ready
      - name: Wait for Server
        run: |
          timeout 1500 bash -c '
          until curl --silent --fail ${{ env.TOOLJET_HOST }}; do
            sleep 5
          done'

      # Step 9: Create Cypress environment file
      - name: Create Cypress Environment File
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_SECRETS }}
          dir: "./cypress-tests"

      # Step 10: Run Cypress Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./cypress-tests
          config: "baseUrl=${{ env.TOOLJET_HOST }}"
          config-file: cypress-app-builder.config.js

      # Step 11: Capture Screenshots
      - name: Capture Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: cypress-tests/cypress/screenshots

  Cypress-App-builder-Subpath:
    runs-on: ubuntu-22.04

    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'run-cypress-app-builder-subpath' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Create Docker Buildx builder with platform configuration
      - name: Set up Docker Buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -SL https://github.com/docker/buildx/releases/download/v0.11.0/buildx-v0.11.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx create --name mybuilder --platform linux/arm64,linux/amd64,linux/amd64/v2,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          docker buildx use mybuilder

      - name: Set DOCKER_CLI_EXPERIMENTAL
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: use mybuilder buildx
        run: docker buildx use mybuilder

      - name: Build docker image
        run: docker buildx build --platform=linux/amd64 -f docker/production.Dockerfile  . -t tooljet/tj-osv:cypressplaform

      - name: Set up environment variables
        run: |
          echo "TOOLJET_HOST=http://localhost:3000" >> .env
          echo "LOCKBOX_MASTER_KEY=cd97331a419c09387bef49787f7da8d2a81d30733f0de6bed23ad8356d2068b2" >> .env
          echo "SECRET_KEY_BASE=7073b9a35a15dd20914ae17e36a693093f25b74b96517a5fec461fc901c51e011cd142c731bee48c5081ec8bac321c1f259ef097ef2a16f25df17a3798c03426" >> .env
          echo "PG_DB=tooljet_development" >> .env
          echo "PG_USER=postgres" >> .env
          echo "PG_HOST=postgres" >> .env
          echo "PG_PASS=postgres" >> .env
          echo "PG_PORT=5432" >> .env
          echo "ENABLE_TOOLJET_DB=true" >> .env
          echo "TOOLJET_DB=tooljet_db" >> .env
          echo "TOOLJET_DB_USER=postgres" >> .env
          echo "TOOLJET_DB_HOST=postgres" >> .env
          echo "TOOLJET_DB_PASS=postgres" >> .env
          echo "PGRST_JWT_SECRET=r9iMKoe5CRMgvJBBtp4HrqN7QiPpUToj" >> .env
          echo "PGRST_HOST=postgrest" >> .env
          echo "PGRST_DB_URI=postgres://postgres:postgres@postgres/tooljet_db" >> .env
          echo "SSO_GIT_OAUTH2_CLIENT_ID=dummy" >> .env
          echo "SSO_GIT_OAUTH2_CLIENT_SECRET=dummy" >> .env
          echo "SSO_GIT_OAUTH2_HOST=dummy" >> .env
          echo "SSO_GOOGLE_OAUTH2_CLIENT_ID=dummy" >> .env
          echo "SUB_PATH=/apps/tooljet/" >> .env
          echo "NODE_ENV=production" >> .env
          echo "SERVE_CLIENT=true" >> .env
          echo "ENABLE_PRIVATE_APP_EMBED=true" >> .env

      - name: Pulling the docker-compose file
        run: curl -LO https://tooljet-test.s3.us-west-1.amazonaws.com/docker-compose.yaml && mkdir postgres_data

      - name: Run docker-compose file
        run: docker-compose up -d

      - name: Checking containers
        run: docker ps -a

      - name: docker logs
        run: sudo docker logs Tooljet-app

      - name: Wait for the server to be ready
        run: |
          timeout 1500 bash -c '
          until curl --silent --fail http://localhost:80/apps/tooljet/; do
            sleep 5
          done'

      - name: Seeding
        run: docker exec Tooljet-app npm run db:seed:prod

      - name: Create Cypress environment file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_SECRETS }}
          dir: "./cypress-tests"

      - name: App Builder subpath
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./cypress-tests
          config: "baseUrl=http://localhost:80/apps/tooljet/"
          config-file: cypress-app-builder.config.js

      - name: Capture Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: cypress-tests/cypress/screenshots
