name: Deploy to Netlify

on:
  push:
    branches:
      - automation/netlifydocs
    paths:
      - docs/**
  workflow_dispatch:
  pull_request:
    types: [labeled]
    branches:
      - automation/netlifydocs

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'labeled' &&
      github.event.label.name == 'net-doc'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=build --auth=$NETLIFY_AUTH_TOKEN --site=${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
